-- MySQL Script generated by MySQL Workbench
-- tis  7 nov 2017 09:55:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table ``customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `shipment_name` VARCHAR(45)NOT NULL,
  `shipment_address` VARCHAR(45) NOT NULL,
  `shipment_city` VARCHAR(45) NOT NULL,
  `isAdmin` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT(10) NOT NULL,
  `ininventory` INT(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `customerID` INT(8) NOT NULL,
  `productID` INT(8) NOT NULL,
  `ammountOrdered` INT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_1_idx` (`customerID` ASC),
  UNIQUE INDEX `product_id_UNIQUE` (`productID` ASC),
  UNIQUE INDEX `customer_id_UNIQUE` (`customerID` ASC),
  CONSTRAINT `fk_orders_1`
    FOREIGN KEY (`customerID`)
    REFERENCES `customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_2`
    FOREIGN KEY (`productID`)
    REFERENCES `products` (`id`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Table `orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderdetails` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `product_id` INT(8) NOT NULL,
  `order_id` INT(8) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orderdetails_1_idx` (`product_id` ASC),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC),
  CONSTRAINT `fk_orderdetails_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderdetails_2`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
