-- MySQL Script generated by MySQL Workbench
-- tis  7 nov 2017 09:55:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table ``customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers` (
  `customer_id` INT(8) NOT NULL AUTO_INCREMENT,
  `customer_email` VARCHAR(45) NULL,
  `customer_password` VARCHAR(45) NULL,
  `customer_firstname` VARCHAR(45) NULL,
  `customer_lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_email_UNIQUE` (`customer_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders` (
  `order_id` INT(8) NOT NULL AUTO_INCREMENT,
  `order_user_id` INT(8) NULL,
  `order_shipment_name` VARCHAR(45) NULL,
  `order_shipment_address` VARCHAR(45) NULL,
  `order_shipment_city` VARCHAR(45) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_1_idx` (`order_user_id` ASC),
  CONSTRAINT `fk_orders_1`
    FOREIGN KEY (`order_user_id`)
    REFERENCES `customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products` (
  `product_id` INT(8) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NULL,
  `product_price` INT(10) NULL,
  `product_ininventory` INT(10) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderdetails` (
  `Order_detail_id` INT(8) NOT NULL,
  `product_id` INT(8) NULL,
  `order_id` INT(8) NULL,
  PRIMARY KEY (`Order_detail_id`),
  INDEX `fk_orderdetails_1_idx` (`product_id` ASC),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC),
  CONSTRAINT `fk_orderdetails_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderdetails_2`
    FOREIGN KEY (`order_id`)
    REFERENCES orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
